### ISSUE TITLE
Type hinting / contract hinting

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#30] opened 2018-08-22 11:56 UTC
As an analogy to interfaces in Object Oriented Programming languages, it would provide a basis for best practice coding when there's a kind of type check on each call made out to nodes.

**Comment by loreanvictor** [comment] 2018-08-23 13:02
this is a duplicate of [#11](https://github.com/CONNECT-platform/connect-platform/issues/11).

**Closed by loreanvictor** 2018-08-23 13:02 UTC

**Comment by must** [comment] 2018-08-23 13:06
Just as a little difference to the other issue. I'm talking more type hinting as objects (since most of what's passing is JSON rather than simple types). So it's to be taken into consideration that type hinting as interfaces (again analogy to OOP) could be a powerful way and an extension of the suggestion mentioned in issue #11.
