### ISSUE TITLE
Missing package "event-stream" in dependencies. 

### ISSUE THREAD

**Issue by adrianriddle** [CONNECT-platform/connect-platform#56] opened 2018-12-13 12:58 UTC
When installing on a local machine using npm i:
404 Not Found: event-stream@3.3.6

That version is not available on npm, possibly due to the hack on that library.

**Comment by loreanvictor** [comment] 2018-12-13 14:04
thanks for the issue. I forgot to update the package-lock file after that fiasco basically. it should be fixed now.

**Comment by loreanvictor** [comment] 2018-12-13 14:05
closing the issue for now. if the issue persists, feel free to re-open it.

**Closed** 2018-12-13 14:05 UTC

**Comment by loreanvictor** [comment] 2018-12-14 12:52
yes I believe connect-platform-boilerplate uses the NPM package. should be fixed now.

**Comment by adrianriddle** [comment] 2018-12-14 13:21
I think you need to update this one too: flatmap-stream@0.1.1

**Comment by loreanvictor** [comment] 2018-12-14 18:19
no it was a case of not properly updated package-lock.json. should work now. if the issue persists, please open an issue on [connect-platform-boilerplate](https://github.com/CONNECT-platform/connect-platform-boilerplate) project since the issue is related to that one.
